name: DAST - scan usando URL funcional mock

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast-mock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OWASP ZAP
        run: sudo snap install zaproxy --classic

      - name: Run ZAP baseline scan
        run: |
          zap-baseline.py \
            -t https://example.com/ \
            -r zap-report.html \
            -J zap-report.json || true

      - name: Install Nikto
        run: |
          sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto scan
        run: |
          nikto -h https://example.com/ -output nikto-report.txt || true

      - name: Check security headers (curl)
        run: |
          echo "=== Security headers for https://example.com/ ===" > headers.txt
          curl -sI https://example.com/ >> headers.txt || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: |
            zap-report.json
            zap-report.html
            nikto-report.txt
            headers.txt
