name: DAST - unauthenticated scans (ZAP + Nikto + headers)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  dast-unauth:
    runs-on: ubuntu-latest
    services:
      # opcional: rode um DB se precisar; se você já tem docker-compose, substitua por step que sobe o compose
    steps:
      - uses: actions/checkout@v4

      - name: Start application (docker-compose staging) - optional
        if: ${{ always() }}
        run: |
          # Se você tem docker-compose.staging.yml no repo, descomente abaixo:
          # docker-compose -f docker-compose.staging.yml up -d
          echo "Assumindo app já disponível em http://localhost:8080 ou adapt to your start command"

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -sSf http://localhost:8080/ >/dev/null 2>&1; then
              echo "app up"; exit 0
            fi
            echo "waiting... ($i)"
            sleep 2
          done
          echo "App did not start" && exit 1

      - name: Install OWASP ZAP
        run: sudo snap install zaproxy --classic

      - name: Run ZAP baseline (unauthenticated)
        run: |
          # Baseline scan (non-authenticated) - gera HTML e JSON
          zap-baseline.py -t http://localhost:8080 -r zap-report.html -J zap-report.json || true

      - name: Install Nikto
        run: |
          sudo apt-get update && sudo apt-get install -y nikto

      - name: Run Nikto scan (unauthenticated)
        run: |
          nikto -h http://localhost:8080 -output nikto-report.txt || true

      - name: Check security headers (curl)
        run: |
          echo "=== Security headers for / ===" > headers.txt
          curl -sI http://localhost:8080 >> headers.txt || true
          echo "" >> headers.txt
          echo "=== Security headers for /health ===" >> headers.txt
          curl -sI http://localhost:8080/health >> headers.txt || true

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: dast-reports
          path: |
            zap-report.json
            zap-report.html
            nikto-report.txt
            headers.txt

      - name: Tear down staging (if used)
        if: ${{ always() }}
        run: |
          # docker-compose -f docker-compose.staging.yml down || true
          echo "done"
