name: DAST - unauthenticated

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t minha-app:latest .

      - name: Run Docker container
        run: |
          docker run -d --name minha-app-container -p 8080:8080 minha-app:latest
          sleep 20

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:8080 && break
            echo "Waiting..."
            sleep 2
          done

      - name: Run Nikto scan
        run: nikto -h http://localhost:8080 -output nikto-report.txt

      - name: Collect HTTP headers
        run: curl -I http://localhost:8080 > headers.txt

      - name: Stop Docker container
        run: docker stop minha-app-container

      - name: Upload Nikto report
        uses: actions/upload-artifact@v4
        with:
          name: nikto-report
          path: nikto-report.txt

      - name: Upload headers
        uses: actions/upload-artifact@v4
        with:
          name: headers
          path: headers.txt
